---
title: "Savings"
format: pdf
editor: visual
---

In overlapping generations models, savings behavior is generally determined via the maximization of some utility function. In its simplest form, utility follows the below structure:

$$
U_t = u(c_t) + \delta u(c_{t+1})
$$

An agent seeks to maximize total utility ($U_t$) which is the sum a "flow" utility function ($u$) applied to consumption in their current time period ($c_t$) and their retired period ($c_{t+1}$). Utility from consumption in the future period is multiplied by a discount factor ($\delta \in (0,1)$).

This equation is subject to the constraints that consumption in the first period is less than or equal to wages, and that consumption in the second period is less than or equal to the sum first period savings and income in period 2, such as through interest return on those savings or perhaps a pension.

Notably, in the special case that $u(c) = log(c)$, savings $s_t$ simplifies to

$$
s_t = \frac{\delta}{1+\delta}w_t
$$

Thus, it may be reasonable for savings to constitute a fixed fraction of wages.

Since our model incorporates heterogeneity, we must consider a difference in savings rates between rich and poor households.

Returning to our savings equation, $$
s_t = \frac{\delta}{1+\delta}w_t
$$

Savings rate differences be rationalized mathematically through differences in $\delta$. Recall that $\delta$ is the discount factor at which agents prioritize future consumption. Heterogeneous savings rates imply that poor agents have lower delta (future consumption has less priority) and rich agents have high delta (future consumption has more priority). There are two key reasons for this. First, poor agents have more immediate consumption needs. Prioritization of future consumption will automatically be lessened if a greater proportion of wages is required for present necessities. Second, rich agents have more access to assets which retain their value, such as real estate and stocks. This can be represented as a higher $\delta$ , not because rich agents are inherently more patient, but because their consumption choices allow them to accumulate wealth passively, making it easier to save for the future without sacrificing consumption in the current period. This is corroberrated by \[[study](https://www.nber.org/system/files/working_papers/w26588/w26588.pdf)\], which found that wealthier households have higher gross savings rates (including capital gains), but found little variation of net savings rates (excluding capital gains) across the wealth distribution. This difference between gross and net savings arises from wealthy consumption of goods which retain their value, and then generate returns.
